version: '3'

services:
  load_balancer:
    image: revoly/nginx
    ports: 
      - "3000:8080"
  mongo:
        image: mongo:latest
        container_name: mongo
        ports:  
          - 27017:27017
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: rootpassword
        volumes:
          - ./data:/data/db
  redis:
        image: redis:latest
        command: redis-server --requirepass root
        ports:
          - 6379:6379
        volumes:
          - ./redisdata:/var/lib/redis
        
  goglot:
    image: revoly/goglot
    ports:
      - 5000:5000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  app1:
    image: revoly/discoded/v2
    environment:
      - ID=1000


