version: '3'

services:
  load_balancer:
    image: revoly/nginx
    ports: 
      - "3000:8080"
  mongo:
        image: mongo:latest
        container_name: mongo
        ports:  
          - 27017:27017
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: rootpassword
        volumes:
          - ./data1:/data/db
  app1:
    image: revoly/discoded
    environment:
      - ID=1000
  
  app2:
    image: revoly/discoded
    environment:
      - ID=2000

  app3:
    image: revoly/discoded
    environment:
      - ID=3000

  app4:
    image: revoly/discoded
    environment:
      - ID=4000
  app5:
    image: revoly/discordbot

  