apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: myapp
        image: mongo:latest
        resources:
        ports:
        - containerPort: 27017
          hostPort: 27017
        env: 
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              configMapKeyRef:
                key: MONGO_INITDB_ROOT_USERNAME
                name: mongo
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              configMapKeyRef:
                key: MONGO_INITDB_ROOT_PASSWORD
                name: mongo
        volumeMounts:
          - name: mongo
            mountPath: /data/db
      volumes:
        - name: mongo
          hostPath:
            path: /data
