name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Build the stack
        run: chmod +x ./main.sh && ./main.sh
      - name: Test
        run: cd tests && npm i &&npm run test