name: Synchronizing and testing.
on: 
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
      
jobs:
  sync:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
      - name: Synchronize
        run: chmod +x ./sync.sh && ./sync.sh
      - uses: actions/setup-node@v1
      - name: Fetch
        run: git fetch
      - name: switch branch
        run: git checkout testing
      - name: Build the stack
        run: chmod +x ./main.sh && ./main.sh
      - name: Test
        run:  cd tests && npm i &&npm run test
