name: Docker Compose Actions Workflow
on: 
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
jobs:
  test:
    needs: sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Build the stack
        run: chmod +x ./main.sh && ./main.sh
      - name: Test
        run:  cd tests && npm i &&npm run test
  sync:
      runs-on: ubuntu-latest
      if: ${GITHUB_REF##*/} != 'testing'
      steps:
      - uses: actions/checkout@v2
      - name: Synchronize
        run: chmod +x ./sync.sh && ./sync.sh